server {
	listen		8080;		# Port number
	server_name	localhost;
	root /var/www/mysite;	# Sets the root directory for requests
	index index.html;		# Default file to serve when requests is a directory
	error_page 404 error_pages/404.html;
	client_max_body_size 2M;

	location / {
		try_files $uri $uri/ = 404;	#look for exact file match, if no display index.html, if none return 404
		methods GET POST DELETE;
		autoindex off;
	}

	location /images/ {
		root /var/www/mysite/data;
		methods GET;
		autoindex on;	# Enabling or disabling directory listing.
	}

	location /redirect {
		return 301 /new;
	}
}

# maybe need upload on off
